import type { Equipment, MuscleGroup } from "@/src/types/gym";

export interface SeedExercise {
  /** Id stabile: permette di riconoscere il seed già inserito. */
  id: string;
  name: string;
  muscleGroup: MuscleGroup;
  secondaryMuscles: MuscleGroup[];
  equipment: Equipment[];
  instructions?: string;
}

export const SEED_EXERCISES: SeedExercise[] = [
  // Petto
  {
    id: "ex-panca-piana-bilanciere",
    name: "Panca piana con bilanciere",
    muscleGroup: "petto",
    secondaryMuscles: ["tricipiti", "spalle"],
    equipment: ["bilanciere", "panca"],
    instructions:
      "Scapole addotte e depresse per tutta la serie, il bilanciere scende all'altezza dei capezzoli.",
  },
  {
    id: "ex-panca-inclinata-bilanciere",
    name: "Panca inclinata con bilanciere",
    muscleGroup: "petto",
    secondaryMuscles: ["spalle", "tricipiti"],
    equipment: ["bilanciere", "panca"],
    instructions:
      "Inclinazione 30-45 gradi: oltre i 45 il lavoro si sposta quasi tutto sulle spalle.",
  },
  {
    id: "ex-panca-declinata-bilanciere",
    name: "Panca declinata con bilanciere",
    muscleGroup: "petto",
    secondaryMuscles: ["tricipiti"],
    equipment: ["bilanciere", "panca"],
  },
  {
    id: "ex-panca-piana-manubri",
    name: "Panca piana con manubri",
    muscleGroup: "petto",
    secondaryMuscles: ["tricipiti", "spalle"],
    equipment: ["manubri", "panca"],
    instructions:
      "Scendi finché i gomiti superano di poco la linea del busto, senza far toccare i manubri in alto.",
  },
  {
    id: "ex-panca-inclinata-manubri",
    name: "Panca inclinata con manubri",
    muscleGroup: "petto",
    secondaryMuscles: ["spalle", "tricipiti"],
    equipment: ["manubri", "panca"],
  },
  {
    id: "ex-panca-declinata-manubri",
    name: "Panca declinata con manubri",
    muscleGroup: "petto",
    secondaryMuscles: ["tricipiti"],
    equipment: ["manubri", "panca"],
  },
  {
    id: "ex-croci-panca-piana-manubri",
    name: "Croci su panca piana con manubri",
    muscleGroup: "petto",
    secondaryMuscles: ["spalle"],
    equipment: ["manubri", "panca"],
    instructions:
      "Gomiti semi-piegati e angolo fisso: se si aprono e chiudono stai facendo una distensione.",
  },
  {
    id: "ex-croci-panca-inclinata-manubri",
    name: "Croci su panca inclinata con manubri",
    muscleGroup: "petto",
    secondaryMuscles: ["spalle"],
    equipment: ["manubri", "panca"],
  },
  {
    id: "ex-chest-press-macchina",
    name: "Chest press alla macchina",
    muscleGroup: "petto",
    secondaryMuscles: ["tricipiti", "spalle"],
    equipment: ["macchina"],
    instructions:
      "Regola il sedile in modo che le maniglie siano all'altezza della parte bassa del petto.",
  },
  {
    id: "ex-pectoral-machine",
    name: "Pectoral machine",
    muscleGroup: "petto",
    secondaryMuscles: ["spalle"],
    equipment: ["macchina"],
  },
  {
    id: "ex-croci-cavi-alti",
    name: "Croci ai cavi alti",
    muscleGroup: "petto",
    secondaryMuscles: ["spalle"],
    equipment: ["cavi"],
    instructions: "Chiudi le mani sotto la linea dello sterno, non davanti al viso.",
  },
  {
    id: "ex-croci-cavi-bassi",
    name: "Croci ai cavi bassi",
    muscleGroup: "petto",
    secondaryMuscles: ["spalle"],
    equipment: ["cavi"],
  },
  {
    id: "ex-chest-press-cavi",
    name: "Chest press ai cavi",
    muscleGroup: "petto",
    secondaryMuscles: ["tricipiti", "spalle"],
    equipment: ["cavi"],
  },
  {
    id: "ex-piegamenti-braccia",
    name: "Piegamenti sulle braccia",
    muscleGroup: "petto",
    secondaryMuscles: ["tricipiti", "spalle", "addome"],
    equipment: ["corpo_libero"],
    instructions: "Corpo in linea dalla testa ai talloni, gomiti a circa 45 gradi dal busto.",
  },
  {
    id: "ex-piegamenti-piedi-rialzati",
    name: "Piegamenti con i piedi rialzati",
    muscleGroup: "petto",
    secondaryMuscles: ["spalle", "tricipiti", "addome"],
    equipment: ["corpo_libero", "panca"],
  },
  {
    id: "ex-piegamenti-presa-larga",
    name: "Piegamenti a presa larga",
    muscleGroup: "petto",
    secondaryMuscles: ["spalle", "tricipiti"],
    equipment: ["corpo_libero"],
  },
  {
    id: "ex-dip-parallele-petto",
    name: "Dip alle parallele per il petto",
    muscleGroup: "petto",
    secondaryMuscles: ["tricipiti", "spalle"],
    equipment: ["corpo_libero"],
    instructions:
      "Busto inclinato in avanti e gomiti leggermente aperti: da verticali diventa un esercizio per i tricipiti.",
  },
  {
    id: "ex-pullover-manubro",
    name: "Pullover con manubro",
    muscleGroup: "petto",
    secondaryMuscles: ["schiena", "tricipiti"],
    equipment: ["manubri", "panca"],
    instructions: "Scendi solo fin dove le spalle restano stabili, senza inarcare la zona lombare.",
  },
  {
    id: "ex-spinte-elastici-petto",
    name: "Spinte con elastici in piedi",
    muscleGroup: "petto",
    secondaryMuscles: ["tricipiti", "spalle"],
    equipment: ["elastici"],
  },

  // Schiena
  {
    id: "ex-stacco-da-terra",
    name: "Stacco da terra",
    muscleGroup: "schiena",
    secondaryMuscles: ["femorali", "glutei", "quadricipiti", "avambracci"],
    equipment: ["bilanciere"],
    instructions: "Schiena neutra, il bilanciere resta a contatto con le gambe per tutta la salita.",
  },
  {
    id: "ex-stacco-sumo",
    name: "Stacco sumo",
    muscleGroup: "schiena",
    secondaryMuscles: ["glutei", "quadricipiti", "femorali", "avambracci"],
    equipment: ["bilanciere"],
    instructions: "Punte dei piedi ruotate in fuori e ginocchia che spingono verso i gomiti.",
  },
  {
    id: "ex-rematore-bilanciere",
    name: "Rematore con bilanciere",
    muscleGroup: "schiena",
    secondaryMuscles: ["bicipiti", "avambracci"],
    equipment: ["bilanciere"],
    instructions: "Busto a circa 45 gradi e fermo: se ti tiri su a ogni ripetizione stai barando.",
  },
  {
    id: "ex-rematore-manubrio-un-braccio",
    name: "Rematore con manubrio a un braccio",
    muscleGroup: "schiena",
    secondaryMuscles: ["bicipiti", "avambracci"],
    equipment: ["manubri", "panca"],
    instructions: "Tira il gomito verso l'anca, non verso la spalla, evitando di ruotare il busto.",
  },
  {
    id: "ex-rematore-pendlay",
    name: "Rematore Pendlay",
    muscleGroup: "schiena",
    secondaryMuscles: ["bicipiti", "avambracci"],
    equipment: ["bilanciere"],
    instructions: "Il bilanciere torna a terra e si ferma a ogni ripetizione, busto parallelo al suolo.",
  },
  {
    id: "ex-rematore-bilanciere-presa-inversa",
    name: "Rematore con bilanciere presa inversa",
    muscleGroup: "schiena",
    secondaryMuscles: ["bicipiti", "avambracci"],
    equipment: ["bilanciere"],
  },
  {
    id: "ex-lat-machine-avanti",
    name: "Lat machine avanti",
    muscleGroup: "schiena",
    secondaryMuscles: ["bicipiti", "avambracci"],
    equipment: ["macchina"],
    instructions: "Porta la barra allo sterno abbassando prima le scapole, senza sdraiarti indietro.",
  },
  {
    id: "ex-lat-machine-presa-inversa",
    name: "Lat machine presa inversa",
    muscleGroup: "schiena",
    secondaryMuscles: ["bicipiti"],
    equipment: ["macchina"],
  },
  {
    id: "ex-lat-machine-presa-stretta",
    name: "Lat machine presa stretta con triangolo",
    muscleGroup: "schiena",
    secondaryMuscles: ["bicipiti"],
    equipment: ["macchina"],
  },
  {
    id: "ex-pulley-basso",
    name: "Pulley basso",
    muscleGroup: "schiena",
    secondaryMuscles: ["bicipiti", "avambracci"],
    equipment: ["macchina"],
    instructions: "Il busto resta quasi verticale: l'oscillazione avanti e indietro toglie lavoro al dorso.",
  },
  {
    id: "ex-trazioni-presa-prona",
    name: "Trazioni alla sbarra presa prona",
    muscleGroup: "schiena",
    secondaryMuscles: ["bicipiti", "avambracci"],
    equipment: ["sbarra"],
    instructions: "Parti da braccia distese attivando le scapole prima di piegare i gomiti.",
  },
  {
    id: "ex-trazioni-presa-supina",
    name: "Trazioni presa supina",
    muscleGroup: "schiena",
    secondaryMuscles: ["bicipiti", "avambracci"],
    equipment: ["sbarra"],
  },
  {
    id: "ex-trazioni-presa-neutra",
    name: "Trazioni presa neutra",
    muscleGroup: "schiena",
    secondaryMuscles: ["bicipiti", "avambracci"],
    equipment: ["sbarra"],
  },
  {
    id: "ex-trazioni-assistite-macchina",
    name: "Trazioni assistite alla macchina",
    muscleGroup: "schiena",
    secondaryMuscles: ["bicipiti"],
    equipment: ["macchina"],
  },
  {
    id: "ex-pulldown-braccia-tese",
    name: "Pulldown ai cavi a braccia tese",
    muscleGroup: "schiena",
    secondaryMuscles: ["tricipiti", "addome"],
    equipment: ["cavi"],
    instructions: "Gomiti bloccati quasi dritti per tutto il movimento, l'arco lo fanno solo le spalle.",
  },
  {
    id: "ex-low-row-macchina",
    name: "Low row alla macchina",
    muscleGroup: "schiena",
    secondaryMuscles: ["bicipiti"],
    equipment: ["macchina"],
  },
  {
    id: "ex-t-bar-row",
    name: "T-bar row",
    muscleGroup: "schiena",
    secondaryMuscles: ["bicipiti", "avambracci"],
    equipment: ["bilanciere"],
  },
  {
    id: "ex-rematore-cavo-un-braccio",
    name: "Rematore ai cavi a un braccio",
    muscleGroup: "schiena",
    secondaryMuscles: ["bicipiti"],
    equipment: ["cavi"],
  },
  {
    id: "ex-iperestensioni-panca-romana",
    name: "Iperestensioni alla panca romana",
    muscleGroup: "schiena",
    secondaryMuscles: ["glutei", "femorali"],
    equipment: ["macchina"],
    instructions: "Fermati quando il corpo è in linea: salire oltre comprime inutilmente le lombari.",
  },
  {
    id: "ex-australian-row-trx",
    name: "Rematore orizzontale al TRX",
    muscleGroup: "schiena",
    secondaryMuscles: ["bicipiti", "addome"],
    equipment: ["trx"],
    instructions: "Più avvicini i piedi al punto di ancoraggio, più l'esercizio diventa facile.",
  },
  {
    id: "ex-rematore-kettlebell",
    name: "Rematore con kettlebell",
    muscleGroup: "schiena",
    secondaryMuscles: ["bicipiti", "avambracci"],
    equipment: ["kettlebell"],
  },
  {
    id: "ex-shrug-bilanciere",
    name: "Shrug con bilanciere",
    muscleGroup: "schiena",
    secondaryMuscles: ["avambracci"],
    equipment: ["bilanciere"],
    instructions: "Solo salita e discesa delle spalle: ruotarle non aggiunge nulla al trapezio.",
  },
  {
    id: "ex-shrug-manubri",
    name: "Shrug con manubri",
    muscleGroup: "schiena",
    secondaryMuscles: ["avambracci"],
    equipment: ["manubri"],
  },
  {
    id: "ex-superman",
    name: "Superman a terra",
    muscleGroup: "schiena",
    secondaryMuscles: ["glutei"],
    equipment: ["corpo_libero"],
  },
  {
    id: "ex-rematore-elastici",
    name: "Rematore con elastici",
    muscleGroup: "schiena",
    secondaryMuscles: ["bicipiti"],
    equipment: ["elastici"],
  },

  // Spalle
  {
    id: "ex-military-press-bilanciere",
    name: "Military press con bilanciere",
    muscleGroup: "spalle",
    secondaryMuscles: ["tricipiti", "addome"],
    equipment: ["bilanciere"],
    instructions:
      "Glutei e addome contratti per non inarcare la schiena, la testa arretra per far passare il bilanciere.",
  },
  {
    id: "ex-lento-avanti-seduto-bilanciere",
    name: "Lento avanti seduto con bilanciere",
    muscleGroup: "spalle",
    secondaryMuscles: ["tricipiti"],
    equipment: ["bilanciere", "panca"],
  },
  {
    id: "ex-shoulder-press-manubri",
    name: "Shoulder press con manubri",
    muscleGroup: "spalle",
    secondaryMuscles: ["tricipiti"],
    equipment: ["manubri", "panca"],
  },
  {
    id: "ex-arnold-press",
    name: "Arnold press",
    muscleGroup: "spalle",
    secondaryMuscles: ["tricipiti"],
    equipment: ["manubri", "panca"],
    instructions: "Parti con i palmi verso di te e ruota progressivamente durante la spinta.",
  },
  {
    id: "ex-shoulder-press-macchina",
    name: "Shoulder press alla macchina",
    muscleGroup: "spalle",
    secondaryMuscles: ["tricipiti"],
    equipment: ["macchina"],
  },
  {
    id: "ex-alzate-laterali-manubri",
    name: "Alzate laterali con manubri",
    muscleGroup: "spalle",
    secondaryMuscles: [],
    equipment: ["manubri"],
    instructions: "Sali fino all'altezza delle spalle guidando con i gomiti, senza slanciare con le gambe.",
  },
  {
    id: "ex-alzate-laterali-cavi",
    name: "Alzate laterali ai cavi",
    muscleGroup: "spalle",
    secondaryMuscles: [],
    equipment: ["cavi"],
  },
  {
    id: "ex-alzate-laterali-macchina",
    name: "Alzate laterali alla macchina",
    muscleGroup: "spalle",
    secondaryMuscles: [],
    equipment: ["macchina"],
  },
  {
    id: "ex-alzate-laterali-elastici",
    name: "Alzate laterali con elastici",
    muscleGroup: "spalle",
    secondaryMuscles: [],
    equipment: ["elastici"],
  },
  {
    id: "ex-alzate-frontali-manubri",
    name: "Alzate frontali con manubri",
    muscleGroup: "spalle",
    secondaryMuscles: [],
    equipment: ["manubri"],
  },
  {
    id: "ex-alzate-frontali-bilanciere",
    name: "Alzate frontali con bilanciere",
    muscleGroup: "spalle",
    secondaryMuscles: [],
    equipment: ["bilanciere"],
  },
  {
    id: "ex-alzate-frontali-cavi",
    name: "Alzate frontali ai cavi",
    muscleGroup: "spalle",
    secondaryMuscles: [],
    equipment: ["cavi"],
  },
  {
    id: "ex-alzate-posteriori-manubri",
    name: "Alzate posteriori con manubri",
    muscleGroup: "spalle",
    secondaryMuscles: ["schiena"],
    equipment: ["manubri"],
    instructions: "Busto quasi parallelo al pavimento, apri le braccia senza avvicinare le scapole.",
  },
  {
    id: "ex-reverse-pectoral-machine",
    name: "Reverse pectoral machine",
    muscleGroup: "spalle",
    secondaryMuscles: ["schiena"],
    equipment: ["macchina"],
  },
  {
    id: "ex-croci-inverse-cavi",
    name: "Croci inverse ai cavi",
    muscleGroup: "spalle",
    secondaryMuscles: ["schiena"],
    equipment: ["cavi"],
  },
  {
    id: "ex-face-pull",
    name: "Face pull ai cavi",
    muscleGroup: "spalle",
    secondaryMuscles: ["schiena"],
    equipment: ["cavi"],
    instructions: "Cavo all'altezza del viso: tira la corda verso la fronte aprendo i gomiti alti.",
  },
  {
    id: "ex-tirate-al-mento-bilanciere",
    name: "Tirate al mento con bilanciere",
    muscleGroup: "spalle",
    secondaryMuscles: ["schiena", "bicipiti"],
    equipment: ["bilanciere"],
    instructions: "Presa poco più larga delle spalle e stop all'altezza dello sterno per non irritare la spalla.",
  },
  {
    id: "ex-tirate-al-mento-cavi",
    name: "Tirate al mento ai cavi",
    muscleGroup: "spalle",
    secondaryMuscles: ["schiena", "bicipiti"],
    equipment: ["cavi"],
  },
  {
    id: "ex-push-press",
    name: "Push press con bilanciere",
    muscleGroup: "spalle",
    secondaryMuscles: ["tricipiti", "quadricipiti", "glutei"],
    equipment: ["bilanciere"],
    instructions: "Breve piegamento di gambe e spinta esplosiva: la pausa in basso annulla la trasmissione.",
  },
  {
    id: "ex-shoulder-press-kettlebell",
    name: "Shoulder press con kettlebell",
    muscleGroup: "spalle",
    secondaryMuscles: ["tricipiti", "addome"],
    equipment: ["kettlebell"],
  },
  {
    id: "ex-pike-push-up",
    name: "Pike push up",
    muscleGroup: "spalle",
    secondaryMuscles: ["tricipiti", "petto"],
    equipment: ["corpo_libero"],
    instructions: "Bacino alto e testa che scende davanti alle mani, non tra le mani.",
  },
  {
    id: "ex-handstand-push-up-muro",
    name: "Handstand push up al muro",
    muscleGroup: "spalle",
    secondaryMuscles: ["tricipiti", "addome"],
    equipment: ["corpo_libero"],
  },

  // Bicipiti
  {
    id: "ex-curl-bilanciere",
    name: "Curl con bilanciere",
    muscleGroup: "bicipiti",
    secondaryMuscles: ["avambracci"],
    equipment: ["bilanciere"],
    instructions: "Gomiti fermi lungo i fianchi: se scappano in avanti il carico passa alle spalle.",
  },
  {
    id: "ex-curl-bilanciere-ez",
    name: "Curl con bilanciere EZ",
    muscleGroup: "bicipiti",
    secondaryMuscles: ["avambracci"],
    equipment: ["bilanciere"],
  },
  {
    id: "ex-curl-manubri",
    name: "Curl con manubri",
    muscleGroup: "bicipiti",
    secondaryMuscles: ["avambracci"],
    equipment: ["manubri"],
  },
  {
    id: "ex-curl-alternato-manubri",
    name: "Curl alternato con manubri",
    muscleGroup: "bicipiti",
    secondaryMuscles: ["avambracci"],
    equipment: ["manubri"],
  },
  {
    id: "ex-curl-a-martello",
    name: "Curl a martello",
    muscleGroup: "bicipiti",
    secondaryMuscles: ["avambracci"],
    equipment: ["manubri"],
  },
  {
    id: "ex-curl-a-martello-cavi-corda",
    name: "Curl a martello ai cavi con corda",
    muscleGroup: "bicipiti",
    secondaryMuscles: ["avambracci"],
    equipment: ["cavi"],
  },
  {
    id: "ex-curl-panca-inclinata-manubri",
    name: "Curl su panca inclinata con manubri",
    muscleGroup: "bicipiti",
    secondaryMuscles: ["avambracci"],
    equipment: ["manubri", "panca"],
    instructions: "Le braccia restano dietro la linea del busto: è quello che allunga il capo lungo.",
  },
  {
    id: "ex-curl-concentrato",
    name: "Curl concentrato",
    muscleGroup: "bicipiti",
    secondaryMuscles: [],
    equipment: ["manubri", "panca"],
  },
  {
    id: "ex-curl-panca-scott",
    name: "Curl alla panca Scott",
    muscleGroup: "bicipiti",
    secondaryMuscles: ["avambracci"],
    equipment: ["bilanciere", "panca"],
    instructions: "Non distendere completamente il gomito in basso, la spalla resta appoggiata al cuscino.",
  },
  {
    id: "ex-spider-curl",
    name: "Spider curl",
    muscleGroup: "bicipiti",
    secondaryMuscles: [],
    equipment: ["manubri", "panca"],
  },
  {
    id: "ex-curl-macchina",
    name: "Curl alla macchina",
    muscleGroup: "bicipiti",
    secondaryMuscles: [],
    equipment: ["macchina"],
  },
  {
    id: "ex-curl-cavi-bassi",
    name: "Curl ai cavi bassi",
    muscleGroup: "bicipiti",
    secondaryMuscles: ["avambracci"],
    equipment: ["cavi"],
  },
  {
    id: "ex-curl-21",
    name: "Curl a 21 con bilanciere",
    muscleGroup: "bicipiti",
    secondaryMuscles: ["avambracci"],
    equipment: ["bilanciere"],
    instructions: "Sette ripetizioni nella metà bassa, sette nella metà alta, sette complete senza pause.",
  },
  {
    id: "ex-curl-kettlebell",
    name: "Curl con kettlebell",
    muscleGroup: "bicipiti",
    secondaryMuscles: ["avambracci"],
    equipment: ["kettlebell"],
  },
  {
    id: "ex-curl-elastici",
    name: "Curl con elastici",
    muscleGroup: "bicipiti",
    secondaryMuscles: ["avambracci"],
    equipment: ["elastici"],
  },
  {
    id: "ex-curl-trx",
    name: "Curl al TRX",
    muscleGroup: "bicipiti",
    secondaryMuscles: ["addome"],
    equipment: ["trx"],
  },

  // Tricipiti
  {
    id: "ex-panca-presa-stretta",
    name: "Panca piana presa stretta",
    muscleGroup: "tricipiti",
    secondaryMuscles: ["petto", "spalle"],
    equipment: ["bilanciere", "panca"],
    instructions: "Mani larghe quanto le spalle e gomiti vicini al busto, non più strette di così.",
  },
  {
    id: "ex-french-press-ez",
    name: "French press con bilanciere EZ",
    muscleGroup: "tricipiti",
    secondaryMuscles: [],
    equipment: ["bilanciere", "panca"],
    instructions: "I gomiti restano fermi e puntati al soffitto, si muovono solo gli avambracci.",
  },
  {
    id: "ex-skull-crusher-manubri",
    name: "Skull crusher con manubri",
    muscleGroup: "tricipiti",
    secondaryMuscles: [],
    equipment: ["manubri", "panca"],
  },
  {
    id: "ex-estensioni-sopra-testa-manubro",
    name: "Estensioni sopra la testa con manubro",
    muscleGroup: "tricipiti",
    secondaryMuscles: [],
    equipment: ["manubri"],
    instructions: "Braccia vicine alle orecchie: il capo lungo lavora solo con la spalla in flessione.",
  },
  {
    id: "ex-estensioni-sopra-testa-cavi",
    name: "Estensioni sopra la testa ai cavi con corda",
    muscleGroup: "tricipiti",
    secondaryMuscles: [],
    equipment: ["cavi"],
  },
  {
    id: "ex-push-down-barra",
    name: "Push down ai cavi con barra",
    muscleGroup: "tricipiti",
    secondaryMuscles: [],
    equipment: ["cavi"],
  },
  {
    id: "ex-push-down-corda",
    name: "Push down ai cavi con corda",
    muscleGroup: "tricipiti",
    secondaryMuscles: [],
    equipment: ["cavi"],
    instructions: "In basso apri le estremità della corda verso l'esterno per completare la contrazione.",
  },
  {
    id: "ex-push-down-presa-inversa",
    name: "Push down presa inversa ai cavi",
    muscleGroup: "tricipiti",
    secondaryMuscles: [],
    equipment: ["cavi"],
  },
  {
    id: "ex-push-down-elastico",
    name: "Push down con elastico",
    muscleGroup: "tricipiti",
    secondaryMuscles: [],
    equipment: ["elastici"],
  },
  {
    id: "ex-kickback-manubri",
    name: "Kickback con manubri",
    muscleGroup: "tricipiti",
    secondaryMuscles: [],
    equipment: ["manubri"],
  },
  {
    id: "ex-kickback-cavi",
    name: "Kickback ai cavi",
    muscleGroup: "tricipiti",
    secondaryMuscles: [],
    equipment: ["cavi"],
  },
  {
    id: "ex-dip-parallele",
    name: "Dip alle parallele",
    muscleGroup: "tricipiti",
    secondaryMuscles: ["petto", "spalle"],
    equipment: ["corpo_libero"],
    instructions: "Busto verticale e gomiti stretti per tenere il lavoro sui tricipiti.",
  },
  {
    id: "ex-dip-tra-due-panche",
    name: "Dip tra due panche",
    muscleGroup: "tricipiti",
    secondaryMuscles: ["spalle"],
    equipment: ["panca"],
  },
  {
    id: "ex-dip-macchina-assistita",
    name: "Dip alla macchina assistita",
    muscleGroup: "tricipiti",
    secondaryMuscles: ["petto", "spalle"],
    equipment: ["macchina"],
  },
  {
    id: "ex-piegamenti-diamante",
    name: "Piegamenti a diamante",
    muscleGroup: "tricipiti",
    secondaryMuscles: ["petto", "spalle"],
    equipment: ["corpo_libero"],
  },
  {
    id: "ex-estensioni-tricipiti-macchina",
    name: "Estensioni tricipiti alla macchina",
    muscleGroup: "tricipiti",
    secondaryMuscles: [],
    equipment: ["macchina"],
  },
  {
    id: "ex-estensioni-tricipiti-trx",
    name: "Estensioni tricipiti al TRX",
    muscleGroup: "tricipiti",
    secondaryMuscles: ["addome"],
    equipment: ["trx"],
  },

  // Quadricipiti
  {
    id: "ex-squat-bilanciere",
    name: "Squat con bilanciere",
    muscleGroup: "quadricipiti",
    secondaryMuscles: ["glutei", "femorali", "addome", "schiena"],
    equipment: ["bilanciere"],
    instructions: "Ginocchia in linea con le punte dei piedi, scendi almeno fino al parallelo mantenendo i talloni a terra.",
  },
  {
    id: "ex-front-squat",
    name: "Front squat",
    muscleGroup: "quadricipiti",
    secondaryMuscles: ["glutei", "addome", "schiena"],
    equipment: ["bilanciere"],
    instructions: "Gomiti alti per tutta l'alzata: se cadono il bilanciere scivola in avanti.",
  },
  {
    id: "ex-zercher-squat",
    name: "Zercher squat",
    muscleGroup: "quadricipiti",
    secondaryMuscles: ["glutei", "addome", "schiena"],
    equipment: ["bilanciere"],
  },
  {
    id: "ex-goblet-squat",
    name: "Goblet squat con kettlebell",
    muscleGroup: "quadricipiti",
    secondaryMuscles: ["glutei", "addome"],
    equipment: ["kettlebell"],
  },
  {
    id: "ex-squat-corpo-libero",
    name: "Squat a corpo libero",
    muscleGroup: "quadricipiti",
    secondaryMuscles: ["glutei"],
    equipment: ["corpo_libero"],
  },
  {
    id: "ex-squat-multipower",
    name: "Squat al multipower",
    muscleGroup: "quadricipiti",
    secondaryMuscles: ["glutei", "femorali"],
    equipment: ["macchina", "bilanciere"],
  },
  {
    id: "ex-hack-squat",
    name: "Hack squat alla macchina",
    muscleGroup: "quadricipiti",
    secondaryMuscles: ["glutei"],
    equipment: ["macchina"],
  },
  {
    id: "ex-leg-press-45",
    name: "Leg press 45 gradi",
    muscleGroup: "quadricipiti",
    secondaryMuscles: ["glutei", "femorali"],
    equipment: ["macchina"],
    instructions: "Fermati prima che il bacino si stacchi dallo schienale e non bloccare le ginocchia in alto.",
  },
  {
    id: "ex-leg-extension",
    name: "Leg extension",
    muscleGroup: "quadricipiti",
    secondaryMuscles: [],
    equipment: ["macchina"],
  },
  {
    id: "ex-affondi-manubri",
    name: "Affondi con manubri",
    muscleGroup: "quadricipiti",
    secondaryMuscles: ["glutei", "femorali"],
    equipment: ["manubri"],
  },
  {
    id: "ex-affondi-camminati-bilanciere",
    name: "Affondi camminati con bilanciere",
    muscleGroup: "quadricipiti",
    secondaryMuscles: ["glutei", "femorali", "addome"],
    equipment: ["bilanciere"],
  },
  {
    id: "ex-affondi-indietro",
    name: "Affondi indietro a corpo libero",
    muscleGroup: "quadricipiti",
    secondaryMuscles: ["glutei"],
    equipment: ["corpo_libero"],
  },
  {
    id: "ex-bulgarian-split-squat",
    name: "Bulgarian split squat",
    muscleGroup: "quadricipiti",
    secondaryMuscles: ["glutei", "femorali"],
    equipment: ["manubri", "panca"],
    instructions: "Più avanti metti il piede d'appoggio, più il lavoro passa dal quadricipite al gluteo.",
  },
  {
    id: "ex-step-up-panca-manubri",
    name: "Step up su panca con manubri",
    muscleGroup: "quadricipiti",
    secondaryMuscles: ["glutei"],
    equipment: ["manubri", "panca"],
    instructions: "Spingi con la gamba sopra senza darti la spinta con il piede a terra.",
  },
  {
    id: "ex-sissy-squat",
    name: "Sissy squat",
    muscleGroup: "quadricipiti",
    secondaryMuscles: [],
    equipment: ["corpo_libero"],
    instructions: "Ginocchia avanti e bacino in linea con le spalle, il busto si inclina indietro.",
  },
  {
    id: "ex-wall-sit",
    name: "Wall sit",
    muscleGroup: "quadricipiti",
    secondaryMuscles: ["glutei"],
    equipment: ["corpo_libero"],
  },
  {
    id: "ex-pistol-squat",
    name: "Pistol squat",
    muscleGroup: "quadricipiti",
    secondaryMuscles: ["glutei", "addome"],
    equipment: ["corpo_libero"],
  },
  {
    id: "ex-jump-squat",
    name: "Jump squat",
    muscleGroup: "quadricipiti",
    secondaryMuscles: ["glutei", "polpacci"],
    equipment: ["corpo_libero"],
    instructions: "Atterra sull'avampiede ammortizzando con le ginocchia morbide.",
  },
  {
    id: "ex-squat-elastico",
    name: "Squat con elastico",
    muscleGroup: "quadricipiti",
    secondaryMuscles: ["glutei"],
    equipment: ["elastici"],
  },

  // Femorali
  {
    id: "ex-stacco-rumeno-bilanciere",
    name: "Stacco rumeno con bilanciere",
    muscleGroup: "femorali",
    secondaryMuscles: ["glutei", "schiena"],
    equipment: ["bilanciere"],
    instructions: "Porta indietro il bacino con le ginocchia quasi ferme, scendi solo finché la schiena resta neutra.",
  },
  {
    id: "ex-stacco-rumeno-manubri",
    name: "Stacco rumeno con manubri",
    muscleGroup: "femorali",
    secondaryMuscles: ["glutei", "schiena"],
    equipment: ["manubri"],
  },
  {
    id: "ex-stacco-rumeno-kettlebell",
    name: "Stacco rumeno con kettlebell",
    muscleGroup: "femorali",
    secondaryMuscles: ["glutei", "schiena"],
    equipment: ["kettlebell"],
  },
  {
    id: "ex-stacco-rumeno-una-gamba",
    name: "Stacco rumeno a una gamba con manubrio",
    muscleGroup: "femorali",
    secondaryMuscles: ["glutei", "schiena"],
    equipment: ["manubri"],
    instructions: "Bacino chiuso, senza far ruotare l'anca della gamba sollevata verso l'esterno.",
  },
  {
    id: "ex-stacco-gambe-tese",
    name: "Stacco a gambe tese",
    muscleGroup: "femorali",
    secondaryMuscles: ["glutei", "schiena"],
    equipment: ["bilanciere"],
  },
  {
    id: "ex-good-morning",
    name: "Good morning con bilanciere",
    muscleGroup: "femorali",
    secondaryMuscles: ["glutei", "schiena"],
    equipment: ["bilanciere"],
    instructions: "Carico leggero e schiena neutra: la leva è lunga e la zona lombare va molto sotto stress.",
  },
  {
    id: "ex-leg-curl-sdraiato",
    name: "Leg curl sdraiato",
    muscleGroup: "femorali",
    secondaryMuscles: ["polpacci"],
    equipment: ["macchina"],
  },
  {
    id: "ex-leg-curl-seduto",
    name: "Leg curl seduto",
    muscleGroup: "femorali",
    secondaryMuscles: ["polpacci"],
    equipment: ["macchina"],
  },
  {
    id: "ex-leg-curl-in-piedi",
    name: "Leg curl in piedi a una gamba",
    muscleGroup: "femorali",
    secondaryMuscles: [],
    equipment: ["macchina"],
  },
  {
    id: "ex-nordic-curl",
    name: "Nordic curl",
    muscleGroup: "femorali",
    secondaryMuscles: ["glutei"],
    equipment: ["corpo_libero"],
    instructions: "Scendi il più lentamente possibile tenendo il bacino esteso, mani pronte a frenare a terra.",
  },
  {
    id: "ex-glute-ham-raise",
    name: "Glute ham raise",
    muscleGroup: "femorali",
    secondaryMuscles: ["glutei", "schiena"],
    equipment: ["macchina"],
  },
  {
    id: "ex-hyperextension-45",
    name: "Hyperextension a 45 gradi",
    muscleGroup: "femorali",
    secondaryMuscles: ["glutei", "schiena"],
    equipment: ["macchina"],
  },
  {
    id: "ex-leg-curl-trx",
    name: "Leg curl al TRX",
    muscleGroup: "femorali",
    secondaryMuscles: ["glutei", "addome"],
    equipment: ["trx"],
    instructions: "Tieni il bacino alto per tutta la serie, non lasciarlo cadere quando pieghi le ginocchia.",
  },
  {
    id: "ex-leg-curl-elastico",
    name: "Leg curl con elastico",
    muscleGroup: "femorali",
    secondaryMuscles: [],
    equipment: ["elastici"],
  },

  // Glutei
  {
    id: "ex-hip-thrust-bilanciere",
    name: "Hip thrust con bilanciere",
    muscleGroup: "glutei",
    secondaryMuscles: ["femorali", "quadricipiti"],
    equipment: ["bilanciere", "panca"],
    instructions: "In alto chiudi il bacino con l'addome, senza inarcare la schiena per salire di più.",
  },
  {
    id: "ex-hip-thrust-macchina",
    name: "Hip thrust alla macchina",
    muscleGroup: "glutei",
    secondaryMuscles: ["femorali"],
    equipment: ["macchina"],
  },
  {
    id: "ex-hip-thrust-una-gamba",
    name: "Hip thrust a una gamba",
    muscleGroup: "glutei",
    secondaryMuscles: ["femorali"],
    equipment: ["corpo_libero", "panca"],
  },
  {
    id: "ex-glute-bridge",
    name: "Glute bridge a terra",
    muscleGroup: "glutei",
    secondaryMuscles: ["femorali"],
    equipment: ["corpo_libero"],
  },
  {
    id: "ex-frog-pump",
    name: "Frog pump",
    muscleGroup: "glutei",
    secondaryMuscles: [],
    equipment: ["corpo_libero"],
  },
  {
    id: "ex-abduttori-macchina",
    name: "Abduttori alla macchina",
    muscleGroup: "glutei",
    secondaryMuscles: [],
    equipment: ["macchina"],
  },
  {
    id: "ex-abduzione-anca-cavi",
    name: "Abduzione dell'anca ai cavi",
    muscleGroup: "glutei",
    secondaryMuscles: [],
    equipment: ["cavi"],
  },
  {
    id: "ex-slanci-posteriori-cavi",
    name: "Slanci posteriori ai cavi",
    muscleGroup: "glutei",
    secondaryMuscles: ["femorali"],
    equipment: ["cavi"],
    instructions: "Il movimento è solo dell'anca: se la schiena si inarca stai usando le lombari.",
  },
  {
    id: "ex-slanci-quadrupedia",
    name: "Slanci posteriori a quattro zampe",
    muscleGroup: "glutei",
    secondaryMuscles: ["femorali"],
    equipment: ["corpo_libero"],
  },
  {
    id: "ex-monster-walk-elastico",
    name: "Camminata laterale con elastico",
    muscleGroup: "glutei",
    secondaryMuscles: ["quadricipiti"],
    equipment: ["elastici"],
  },
  {
    id: "ex-affondi-laterali",
    name: "Affondi laterali",
    muscleGroup: "glutei",
    secondaryMuscles: ["quadricipiti", "femorali"],
    equipment: ["corpo_libero"],
  },
  {
    id: "ex-step-up-alto",
    name: "Step up alto a corpo libero",
    muscleGroup: "glutei",
    secondaryMuscles: ["quadricipiti"],
    equipment: ["corpo_libero"],
    instructions: "Serve un rialzo sopra l'altezza del ginocchio, altrimenti lavora soprattutto il quadricipite.",
  },
  {
    id: "ex-sumo-squat-manubro",
    name: "Sumo squat con manubro",
    muscleGroup: "glutei",
    secondaryMuscles: ["quadricipiti", "femorali"],
    equipment: ["manubri"],
  },
  {
    id: "ex-kettlebell-swing",
    name: "Kettlebell swing",
    muscleGroup: "glutei",
    secondaryMuscles: ["femorali", "schiena", "addome"],
    equipment: ["kettlebell"],
    instructions: "La kettlebell sale per la spinta d'anca, non perché la alzi con le braccia.",
  },

  // Polpacci
  {
    id: "ex-calf-raise-in-piedi-macchina",
    name: "Calf raise in piedi alla macchina",
    muscleGroup: "polpacci",
    secondaryMuscles: [],
    equipment: ["macchina"],
    instructions: "Scendi in allungo completo sotto il livello del gradino prima di risalire.",
  },
  {
    id: "ex-calf-raise-seduto-macchina",
    name: "Calf raise seduto alla macchina",
    muscleGroup: "polpacci",
    secondaryMuscles: [],
    equipment: ["macchina"],
    instructions: "Con il ginocchio piegato lavora soprattutto il soleo: usa carichi più bassi e ripetizioni alte.",
  },
  {
    id: "ex-calf-raise-leg-press",
    name: "Calf raise al leg press",
    muscleGroup: "polpacci",
    secondaryMuscles: [],
    equipment: ["macchina"],
  },
  {
    id: "ex-donkey-calf-raise",
    name: "Donkey calf raise",
    muscleGroup: "polpacci",
    secondaryMuscles: [],
    equipment: ["macchina"],
  },
  {
    id: "ex-calf-raise-manubri",
    name: "Calf raise in piedi con manubri",
    muscleGroup: "polpacci",
    secondaryMuscles: ["avambracci"],
    equipment: ["manubri"],
  },
  {
    id: "ex-calf-raise-bilanciere",
    name: "Calf raise con bilanciere",
    muscleGroup: "polpacci",
    secondaryMuscles: [],
    equipment: ["bilanciere"],
  },
  {
    id: "ex-calf-raise-una-gamba",
    name: "Calf raise a una gamba a corpo libero",
    muscleGroup: "polpacci",
    secondaryMuscles: [],
    equipment: ["corpo_libero"],
  },
  {
    id: "ex-calf-raise-elastico",
    name: "Calf raise con elastico",
    muscleGroup: "polpacci",
    secondaryMuscles: [],
    equipment: ["elastici"],
  },

  // Addome
  {
    id: "ex-crunch-a-terra",
    name: "Crunch a terra",
    muscleGroup: "addome",
    secondaryMuscles: [],
    equipment: ["corpo_libero"],
    instructions: "Stacca solo le scapole arrotondando la schiena, non tirare il collo con le mani.",
  },
  {
    id: "ex-crunch-inverso",
    name: "Crunch inverso",
    muscleGroup: "addome",
    secondaryMuscles: [],
    equipment: ["corpo_libero"],
    instructions: "Solleva il bacino dal pavimento: se muovi solo le gambe lavorano i flessori dell'anca.",
  },
  {
    id: "ex-crunch-cavi",
    name: "Crunch ai cavi in ginocchio",
    muscleGroup: "addome",
    secondaryMuscles: [],
    equipment: ["cavi"],
    instructions: "Il bacino resta fermo, avvicini le costole al pube arrotondando la schiena.",
  },
  {
    id: "ex-crunch-macchina",
    name: "Crunch alla macchina",
    muscleGroup: "addome",
    secondaryMuscles: [],
    equipment: ["macchina"],
  },
  {
    id: "ex-sit-up",
    name: "Sit up",
    muscleGroup: "addome",
    secondaryMuscles: ["quadricipiti"],
    equipment: ["corpo_libero"],
  },
  {
    id: "ex-plank",
    name: "Plank",
    muscleGroup: "addome",
    secondaryMuscles: ["spalle", "glutei"],
    equipment: ["corpo_libero"],
    instructions: "Retroverti leggermente il bacino e contrai i glutei per togliere il carico dalle lombari.",
  },
  {
    id: "ex-plank-laterale",
    name: "Plank laterale",
    muscleGroup: "addome",
    secondaryMuscles: ["spalle", "glutei"],
    equipment: ["corpo_libero"],
  },
  {
    id: "ex-body-saw-trx",
    name: "Body saw al TRX",
    muscleGroup: "addome",
    secondaryMuscles: ["spalle"],
    equipment: ["trx"],
  },
  {
    id: "ex-mountain-climber",
    name: "Mountain climber",
    muscleGroup: "addome",
    secondaryMuscles: ["spalle", "quadricipiti"],
    equipment: ["corpo_libero"],
  },
  {
    id: "ex-dead-bug",
    name: "Dead bug",
    muscleGroup: "addome",
    secondaryMuscles: [],
    equipment: ["corpo_libero"],
    instructions: "La zona lombare resta schiacciata a terra: scendi solo fin dove riesci a tenerla aderente.",
  },
  {
    id: "ex-hollow-hold",
    name: "Hollow hold",
    muscleGroup: "addome",
    secondaryMuscles: [],
    equipment: ["corpo_libero"],
  },
  {
    id: "ex-v-up",
    name: "V-up",
    muscleGroup: "addome",
    secondaryMuscles: [],
    equipment: ["corpo_libero"],
  },
  {
    id: "ex-bicycle-crunch",
    name: "Bicycle crunch",
    muscleGroup: "addome",
    secondaryMuscles: [],
    equipment: ["corpo_libero"],
  },
  {
    id: "ex-russian-twist",
    name: "Russian twist",
    muscleGroup: "addome",
    secondaryMuscles: [],
    equipment: ["corpo_libero"],
  },
  {
    id: "ex-russian-twist-kettlebell",
    name: "Russian twist con kettlebell",
    muscleGroup: "addome",
    secondaryMuscles: [],
    equipment: ["kettlebell"],
  },
  {
    id: "ex-leg-raise-a-terra",
    name: "Sollevamento gambe a terra",
    muscleGroup: "addome",
    secondaryMuscles: [],
    equipment: ["corpo_libero"],
  },
  {
    id: "ex-leg-raise-sbarra",
    name: "Sollevamento gambe alla sbarra",
    muscleGroup: "addome",
    secondaryMuscles: ["avambracci"],
    equipment: ["sbarra"],
    instructions: "Evita l'oscillazione: parti da fermo e chiudi il bacino alla fine del movimento.",
  },
  {
    id: "ex-toes-to-bar",
    name: "Toes to bar",
    muscleGroup: "addome",
    secondaryMuscles: ["schiena", "avambracci"],
    equipment: ["sbarra"],
  },
  {
    id: "ex-sollevamento-ginocchia-parallele",
    name: "Sollevamento ginocchia alle parallele",
    muscleGroup: "addome",
    secondaryMuscles: ["spalle"],
    equipment: ["macchina"],
  },
  {
    id: "ex-rollout-bilanciere",
    name: "Rollout con bilanciere",
    muscleGroup: "addome",
    secondaryMuscles: ["schiena", "spalle"],
    equipment: ["bilanciere"],
    instructions: "Allontanati solo fino al punto in cui la schiena non si inarca, poi torna indietro.",
  },
  {
    id: "ex-woodchopper-cavi",
    name: "Woodchopper ai cavi",
    muscleGroup: "addome",
    secondaryMuscles: ["spalle", "glutei"],
    equipment: ["cavi"],
  },
  {
    id: "ex-pallof-press",
    name: "Pallof press ai cavi",
    muscleGroup: "addome",
    secondaryMuscles: ["spalle"],
    equipment: ["cavi"],
    instructions: "Il busto non deve ruotare: resisti alla trazione del cavo mentre distendi le braccia.",
  },
  {
    id: "ex-side-bend-manubrio",
    name: "Side bend con manubrio",
    muscleGroup: "addome",
    secondaryMuscles: ["avambracci"],
    equipment: ["manubri"],
    instructions: "Un manubrio solo: con due i carichi si annullano e l'esercizio perde senso.",
  },

  // Avambracci
  {
    id: "ex-curl-polsi-bilanciere",
    name: "Curl ai polsi con bilanciere",
    muscleGroup: "avambracci",
    secondaryMuscles: [],
    equipment: ["bilanciere", "panca"],
    instructions: "Avambracci appoggiati alla panca, si muovono solo i polsi.",
  },
  {
    id: "ex-curl-polsi-inverso-bilanciere",
    name: "Curl ai polsi inverso con bilanciere",
    muscleGroup: "avambracci",
    secondaryMuscles: [],
    equipment: ["bilanciere", "panca"],
  },
  {
    id: "ex-curl-polsi-manubri",
    name: "Curl ai polsi con manubri",
    muscleGroup: "avambracci",
    secondaryMuscles: [],
    equipment: ["manubri", "panca"],
  },
  {
    id: "ex-curl-inverso-ez",
    name: "Curl inverso con bilanciere EZ",
    muscleGroup: "avambracci",
    secondaryMuscles: ["bicipiti"],
    equipment: ["bilanciere"],
  },
  {
    id: "ex-zottman-curl",
    name: "Zottman curl",
    muscleGroup: "avambracci",
    secondaryMuscles: ["bicipiti"],
    equipment: ["manubri"],
    instructions: "Sali con i palmi in su, ruota in alto e scendi lentamente con i palmi in giù.",
  },
  {
    id: "ex-farmer-walk-manubri",
    name: "Farmer's walk con manubri",
    muscleGroup: "avambracci",
    secondaryMuscles: ["schiena", "addome"],
    equipment: ["manubri"],
  },
  {
    id: "ex-dead-hang-sbarra",
    name: "Dead hang alla sbarra",
    muscleGroup: "avambracci",
    secondaryMuscles: ["schiena"],
    equipment: ["sbarra"],
  },

  // Full body
  {
    id: "ex-burpee",
    name: "Burpee",
    muscleGroup: "full_body",
    secondaryMuscles: ["petto", "quadricipiti", "spalle", "addome"],
    equipment: ["corpo_libero"],
  },
  {
    id: "ex-thruster-bilanciere",
    name: "Thruster con bilanciere",
    muscleGroup: "full_body",
    secondaryMuscles: ["quadricipiti", "spalle", "glutei", "tricipiti"],
    equipment: ["bilanciere"],
    instructions: "Un unico movimento continuo: la spinta delle gambe si trasmette al bilanciere senza pause.",
  },
  {
    id: "ex-power-clean",
    name: "Girata al petto con bilanciere",
    muscleGroup: "full_body",
    secondaryMuscles: ["quadricipiti", "glutei", "schiena", "spalle"],
    equipment: ["bilanciere"],
    instructions: "Prima estendi completamente anche e ginocchia, solo dopo passi sotto al bilanciere.",
  },
  {
    id: "ex-clean-and-jerk",
    name: "Clean and jerk",
    muscleGroup: "full_body",
    secondaryMuscles: ["quadricipiti", "glutei", "spalle", "schiena"],
    equipment: ["bilanciere"],
  },
  {
    id: "ex-snatch-bilanciere",
    name: "Strappo con bilanciere",
    muscleGroup: "full_body",
    secondaryMuscles: ["spalle", "schiena", "quadricipiti", "glutei"],
    equipment: ["bilanciere"],
  },
  {
    id: "ex-turkish-get-up",
    name: "Turkish get up con kettlebell",
    muscleGroup: "full_body",
    secondaryMuscles: ["spalle", "addome", "glutei"],
    equipment: ["kettlebell"],
    instructions: "Il braccio con il peso resta verticale e l'occhio fisso sulla kettlebell per tutta la salita.",
  },
  {
    id: "ex-kettlebell-clean-and-press",
    name: "Kettlebell clean and press",
    muscleGroup: "full_body",
    secondaryMuscles: ["spalle", "glutei", "schiena"],
    equipment: ["kettlebell"],
  },
  {
    id: "ex-man-maker",
    name: "Man maker con manubri",
    muscleGroup: "full_body",
    secondaryMuscles: ["petto", "schiena", "spalle", "addome"],
    equipment: ["manubri"],
  },
  {
    id: "ex-devil-press",
    name: "Devil press con manubri",
    muscleGroup: "full_body",
    secondaryMuscles: ["spalle", "petto", "glutei"],
    equipment: ["manubri"],
  },
  {
    id: "ex-bear-crawl",
    name: "Bear crawl",
    muscleGroup: "full_body",
    secondaryMuscles: ["addome", "spalle", "quadricipiti"],
    equipment: ["corpo_libero"],
    instructions: "Ginocchia a pochi centimetri da terra e bacino basso, senza far oscillare i fianchi.",
  },
  {
    id: "ex-jumping-jack",
    name: "Jumping jack",
    muscleGroup: "full_body",
    secondaryMuscles: ["polpacci", "spalle"],
    equipment: ["corpo_libero"],
  },
  {
    id: "ex-salto-della-corda",
    name: "Salto della corda",
    muscleGroup: "full_body",
    secondaryMuscles: ["polpacci", "avambracci"],
    equipment: ["cardio"],
  },
  {
    id: "ex-vogatore",
    name: "Vogatore",
    muscleGroup: "full_body",
    secondaryMuscles: ["schiena", "quadricipiti", "bicipiti"],
    equipment: ["cardio"],
    instructions: "Sequenza gambe, busto, braccia in trazione e l'inverso in ritorno.",
  },
  {
    id: "ex-tapis-roulant",
    name: "Corsa sul tapis roulant",
    muscleGroup: "full_body",
    secondaryMuscles: ["quadricipiti", "polpacci", "femorali"],
    equipment: ["cardio"],
  },
  {
    id: "ex-ellittica",
    name: "Ellittica",
    muscleGroup: "full_body",
    secondaryMuscles: ["quadricipiti", "glutei", "spalle"],
    equipment: ["cardio"],
  },
  {
    id: "ex-assault-bike",
    name: "Assault bike",
    muscleGroup: "full_body",
    secondaryMuscles: ["quadricipiti", "spalle", "schiena"],
    equipment: ["cardio"],
  },
];
